import { Project, Page, KanbanCard } from '@/lib/types/database'

const SEED_USERS = [
  {
    id: '1',
    email: 'john@example.com',
    name: 'John Doe',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=John',
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '2',
    email: 'sarah@example.com',
    name: 'Sarah Smith',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah',
    createdAt: new Date('2024-01-02'),
  },
  {
    id: '3',
    email: 'mike@example.com',
    name: 'Mike Johnson',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Mike',
    createdAt: new Date('2024-01-03'),
  },
  {
    id: '4',
    email: 'emily@example.com',
    name: 'Emily Davis',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Emily',
    createdAt: new Date('2024-01-04'),
  },
]

export const SEED_PROJECTS: Project[] = [
  {
    id: 'proj-1',
    name: 'Product Roadmap Q1 2025',
    description: 'Quarterly planning and feature prioritization',
    ownerId: '1',
    avatar: 'https://api.dicebear.com/7.x/shapes/svg?seed=Product',
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-10-27'),
    members: [
      {
        id: 'member-1',
        projectId: 'proj-1',
        userId: '1',
        user: SEED_USERS[0],
        role: 'owner',
        joinedAt: new Date('2024-01-10'),
      },
      {
        id: 'member-2',
        projectId: 'proj-1',
        userId: '2',
        user: SEED_USERS[1],
        role: 'admin',
        joinedAt: new Date('2024-01-11'),
      },
      {
        id: 'member-3',
        projectId: 'proj-1',
        userId: '3',
        user: SEED_USERS[2],
        role: 'editor',
        joinedAt: new Date('2024-01-12'),
      },
    ],
  },
  {
    id: 'proj-2',
    name: 'Engineering Documentation',
    description: 'API docs, architecture guides, and technical specs',
    ownerId: '2',
    avatar: 'https://api.dicebear.com/7.x/shapes/svg?seed=Engineering',
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-10-26'),
    members: [
      {
        id: 'member-4',
        projectId: 'proj-2',
        userId: '2',
        user: SEED_USERS[1],
        role: 'owner',
        joinedAt: new Date('2024-02-01'),
      },
      {
        id: 'member-5',
        projectId: 'proj-2',
        userId: '1',
        user: SEED_USERS[0],
        role: 'editor',
        joinedAt: new Date('2024-02-02'),
      },
      {
        id: 'member-6',
        projectId: 'proj-2',
        userId: '4',
        user: SEED_USERS[3],
        role: 'viewer',
        joinedAt: new Date('2024-02-03'),
      },
    ],
  },
  {
    id: 'proj-3',
    name: 'Marketing Campaign 2025',
    description: 'Campaign planning, assets, and launch timeline',
    ownerId: '3',
    avatar: 'https://api.dicebear.com/7.x/shapes/svg?seed=Marketing',
    createdAt: new Date('2024-03-05'),
    updatedAt: new Date('2024-10-25'),
    members: [
      {
        id: 'member-7',
        projectId: 'proj-3',
        userId: '3',
        user: SEED_USERS[2],
        role: 'owner',
        joinedAt: new Date('2024-03-05'),
      },
      {
        id: 'member-8',
        projectId: 'proj-3',
        userId: '4',
        user: SEED_USERS[3],
        role: 'editor',
        joinedAt: new Date('2024-03-06'),
      },
    ],
  },
]

export const SEED_PAGES: Page[] = [
  {
    id: 'page-1',
    projectId: 'proj-1',
    title: 'Getting Started Guide',
    content:
      '<h2>Welcome to Quill Sync</h2><p>Quill Sync is a collaborative project management tool that combines the best of Confluence and Jira.</p><h3>Key Features</h3><ul><li>Real-time collaborative editing</li><li>Kanban boards for task management</li><li>Version history and rollback</li><li>@mentions and notifications</li></ul>',
    parentId: undefined,
    order: 1,
    createdBy: '1',
    createdAt: new Date('2024-01-10'),
    updatedBy: '1',
    updatedAt: new Date('2024-10-27'),
    versions: [],
  },
  {
    id: 'page-2',
    projectId: 'proj-1',
    title: 'Sprint 24 Planning',
    content:
      '<h2>Sprint 24 - Oct 28 to Nov 10</h2><p>This sprint focuses on performance improvements and bug fixes.</p><h3>Goals</h3><ul><li>Reduce page load time by 20%</li><li>Fix critical UI bugs</li><li>Implement new search feature</li></ul>',
    parentId: undefined,
    order: 2,
    createdBy: '2',
    createdAt: new Date('2024-10-20'),
    updatedBy: '2',
    updatedAt: new Date('2024-10-26'),
    versions: [],
  },
  {
    id: 'page-3',
    projectId: 'proj-2',
    title: 'API Reference',
    content:
      '<h2>Quill Sync API Reference</h2><p>Complete API documentation for Quill Sync integration.</p><h3>Authentication</h3><p>All requests require a valid API token in the Authorization header.</p>',
    parentId: undefined,
    order: 1,
    createdBy: '2',
    createdAt: new Date('2024-02-05'),
    updatedBy: '1',
    updatedAt: new Date('2024-10-25'),
    versions: [],
  },
]

export const SEED_KANBAN_CARDS: KanbanCard[] = [
  {
    id: 'card-1',
    columnId: 'col-1',
    boardId: 'board-1',
    title: 'Design login page mockups',
    description: 'Create high-fidelity mockups for the new login flow',
    labels: [
      {
        id: 'label-1',
        projectId: 'proj-1',
        name: 'Design',
        color: '#8B5CF6',
        createdAt: new Date(),
      },
    ],
    assigneeId: '2',
    assignee: SEED_USERS[1],
    linkedPageId: 'page-1',
    dueDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000),
    order: 1,
    createdBy: '1',
    createdAt: new Date('2024-10-20'),
    updatedAt: new Date('2024-10-27'),
  },
  {
    id: 'card-2',
    columnId: 'col-2',
    boardId: 'board-1',
    title: 'Implement authentication API',
    description: 'Build the backend for user authentication',
    labels: [
      {
        id: 'label-2',
        projectId: 'proj-1',
        name: 'Backend',
        color: '#EC4899',
        createdAt: new Date(),
      },
    ],
    assigneeId: '3',
    assignee: SEED_USERS[2],
    linkedPageId: 'page-3',
    dueDate: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000),
    order: 1,
    createdBy: '1',
    createdAt: new Date('2024-10-18'),
    updatedAt: new Date('2024-10-25'),
  },
  {
    id: 'card-3',
    columnId: 'col-3',
    boardId: 'board-1',
    title: 'Write user guide documentation',
    description: 'Complete documentation for end users',
    labels: [
      {
        id: 'label-3',
        projectId: 'proj-1',
        name: 'Documentation',
        color: '#06B6D4',
        createdAt: new Date(),
      },
    ],
    assigneeId: '1',
    assignee: SEED_USERS[0],
    linkedPageId: 'page-1',
    dueDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    order: 1,
    createdBy: '2',
    createdAt: new Date('2024-10-15'),
    updatedAt: new Date('2024-10-27'),
  },
  {
    id: 'card-4',
    columnId: 'col-1',
    boardId: 'board-1',
    title: 'Bug: Mobile navigation not responsive',
    description: 'Navigation menu breaks on mobile devices below 600px',
    labels: [
      {
        id: 'label-4',
        projectId: 'proj-1',
        name: 'Bug',
        color: '#EF4444',
        createdAt: new Date(),
      },
      {
        id: 'label-5',
        projectId: 'proj-1',
        name: 'Urgent',
        color: '#F59E0B',
        createdAt: new Date(),
      },
    ],
    assigneeId: '3',
    assignee: SEED_USERS[2],
    dueDate: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000),
    order: 2,
    createdBy: '2',
    createdAt: new Date('2024-10-24'),
    updatedAt: new Date('2024-10-26'),
  },
]
